language: cpp

before_install:
# We need this line to have g++4.8 available in apt
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq gcc-4.8 g++-4.8 
# We want to compile with g++ 4.8 when rather than the default g++
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
# Download and install fedlibrary 
  - git clone git://git.code.sf.net/p/fedlibrary/git fedlibrary
  - cd fedlibrary 
  - mkdir build 
  - cd build
  - cmake ../ -DFORCE_PIC=ON 
  - make 
  - make install 
  - ldconfig 
  - cd ../../

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make

branches:
  only:
    - master

