language: cpp

before_install:
# We need this line to have g++5 available in apt
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq gcc-5 g++-5 
# We want to compile with g++ 5 when rather than the default g++
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90

compiler:
  - gcc

before_script:
# Download and install fedlibrary 
  - git clone git://git.code.sf.net/p/fedlibrary/git fedlibrary
  - cd fedlibrary 
  - mkdir build 
  - cd build
  - cmake ../ -DFORCE_PIC=ON 
  - make 
  - sudo make install 
  - sudo ldconfig 
  - cd ../../
# Execute cmake configuration
  - mkdir build
  - cd build
  - cmake ..

script: make

# whitelist
branches:
  only:
    - master

notifications:
  email:
    recipients:
      - fedagostino@gmail.com
    on_success: change
    on_failure: always

